spring.application.name=SpringBoot

spring.datasource.url=jdbc:postgresql://localhost:55000/postgres
spring.datasource.username: postgres
spring.datasource.password: 123456

#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USER}
#spring.datasource.password=${DB_PASSWORD}

#ddl - ?????? ? ???????? ????? ? ??
spring.jpa.hibernate.ddl-auto=update
# ?????????? ??????????? sql ????????
spring.jpa.show-sql=true
# ?????? ????? ? ???????? ????
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.driver-class-name=org.postgresql.Driver



